### ISSUE TITLE
CLA failed pull request

### ISSUE THREAD

**Issue by Bongzy13** [googledatastudio/ds-data-registry#520]
my pull request is keeping on failing allthough I am part of the contributor group and have done all the steps of the procedure. I don't know what to do to get things working with the bot

PR => https://github.com/googledatastudio/ds-data-registry/pull/519

email is correct here => https://patch-diff.githubusercontent.com/raw/googledatastudio/ds-data-registry/pull/519.patch

**Comment by Bongzy13** [comment]
hi, could someone help with this problem?

**Comment by Bongzy13** [comment]
hi, any help would be very appreciated, can someone help me with this issue?

**Comment by pfrisella** [comment]
The sources in #519 were added in #572 so I suspect this isn't an issue for you anymore.
